const fs = require('fs');
const path = require('path');
const AdmZip = require('adm-zip');

const TEMPLATE_DIR = 'C:/tmp/studio1642-work/unpacked';
const OUTPUT_DIR = 'C:/GIT/House of More/Reports';

if (!fs.existsSync(OUTPUT_DIR)) fs.mkdirSync(OUTPUT_DIR, { recursive: true });

const NS = `xmlns:wpc="http://schemas.microsoft.com/office/word/2010/wordprocessingCanvas" xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" xmlns:m="http://schemas.openxmlformats.org/officeDocument/2006/math" xmlns:v="urn:schemas-microsoft-com:vml" xmlns:wp14="http://schemas.microsoft.com/office/word/2010/wordprocessingDrawing" xmlns:wp="http://schemas.openxmlformats.org/drawingml/2006/wordprocessingDrawing" xmlns:w10="urn:schemas-microsoft-com:office:word" xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" xmlns:w14="http://schemas.microsoft.com/office/word/2010/wordml" xmlns:w15="http://schemas.microsoft.com/office/word/2012/wordml" xmlns:w16cex="http://schemas.microsoft.com/office/word/2018/wordml/cex" xmlns:w16cid="http://schemas.microsoft.com/office/word/2016/wordml/cid" xmlns:w16="http://schemas.microsoft.com/office/word/2018/wordml" xmlns:w16se="http://schemas.microsoft.com/office/word/2015/wordml/symex" xmlns:wpg="http://schemas.microsoft.com/office/word/2010/wordprocessingGroup" xmlns:wpi="http://schemas.microsoft.com/office/word/2010/wordprocessingInk" xmlns:wne="http://schemas.microsoft.com/office/word/2006/wordml" xmlns:wps="http://schemas.microsoft.com/office/word/2010/wordprocessingShape" mc:Ignorable="w14 w15 w16se w16cid w16 w16cex wp14"`;

const LOGO = `<w:r><w:rPr><w:noProof/></w:rPr><w:drawing><wp:inline distT="0" distB="0" distL="0" distR="0"><wp:extent cx="2061056" cy="2770495"/><wp:effectExtent l="0" t="0" r="0" b="0"/><wp:docPr id="1301857720" name="Logo"/><wp:cNvGraphicFramePr><a:graphicFrameLocks xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" noChangeAspect="1"/></wp:cNvGraphicFramePr><a:graphic xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main"><a:graphicData uri="http://schemas.openxmlformats.org/drawingml/2006/picture"><pic:pic xmlns:pic="http://schemas.openxmlformats.org/drawingml/2006/picture"><pic:nvPicPr><pic:cNvPr id="1301857720" name="Logo"/><pic:cNvPicPr/></pic:nvPicPr><pic:blipFill rotWithShape="1"><a:blip r:embed="rId6" cstate="print"/><a:stretch><a:fillRect/></a:stretch></pic:blipFill><pic:spPr bwMode="auto"><a:xfrm><a:off x="0" y="0"/><a:ext cx="2068914" cy="2781058"/></a:xfrm><a:prstGeom prst="rect"><a:avLst/></a:prstGeom></pic:spPr></pic:pic></a:graphicData></a:graphic></wp:inline></w:drawing></w:r>`;

const SECTPR = `<w:sectPr><w:headerReference w:type="default" r:id="rId7"/><w:footerReference w:type="default" r:id="rId8"/><w:pgSz w:w="12240" w:h="15840"/><w:pgMar w:top="2268" w:right="720" w:bottom="720" w:left="720" w:header="850" w:footer="170" w:gutter="0"/><w:pgNumType w:start="2"/><w:cols w:space="720"/><w:docGrid w:linePitch="360"/></w:sectPr>`;

const PB = `<w:p><w:r><w:br w:type="page"/></w:r></w:p>`;

const h1 = t => `<w:p><w:pPr><w:pStyle w:val="Heading1"/></w:pPr><w:r><w:t>${t}</w:t></w:r></w:p>`;
const sub = t => `<w:p><w:pPr><w:pStyle w:val="Studio1642"/></w:pPr><w:r><w:t>${t}</w:t></w:r></w:p>`;
const body = t => `<w:p><w:pPr><w:pStyle w:val="Normal"/></w:pPr><w:r><w:t xml:space="preserve">${t}</w:t></w:r></w:p>`;
const li = t => `<w:p><w:pPr><w:pStyle w:val="ListParagraph"/></w:pPr><w:r><w:t xml:space="preserve">&#x2014; ${t}</w:t></w:r></w:p>`;
const sp = () => `<w:p><w:pPr><w:pStyle w:val="Normal"/></w:pPr><w:r><w:t> </w:t></w:r></w:p>`;

function cover(title, subtitle) {
  return `<w:p><w:pPr><w:pStyle w:val="Heading1"/></w:pPr>${LOGO}</w:p>${h1(title)}${sub(subtitle)}${sub('House of More  |  2026  |  thehouseofmore.com')}`;
}

function buildDoc(content) {
  return `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><w:document ${NS}><w:background w:color="F9F8F4"/><w:body>${content}${SECTPR}</w:body></w:document>`;
}

function packDocx(filename, xml) {
  const zip = new AdmZip();
  function addDir(dir, prefix) {
    fs.readdirSync(dir).forEach(f => {
      const full = path.join(dir, f);
      const zp = prefix ? `${prefix}/${f}` : f;
      if (fs.statSync(full).isDirectory()) {
        addDir(full, zp);
      } else if (zp === 'word/document.xml') {
        zip.addFile('word/document.xml', Buffer.from(xml, 'utf8'));
      } else {
        zip.addFile(zp, fs.readFileSync(full));
      }
    });
  }
  addDir(TEMPLATE_DIR, '');
  const out = path.join(OUTPUT_DIR, filename);
  zip.writeZip(out);
  console.log('Written:', out);
}

// ── REPORT 1: FULL AUDIT ──────────────────────────────────────────────────────
packDocx('01-Full-Audit.docx', buildDoc([
  cover('HOUSE OF MORE', 'Site &amp; Automation Audit &#x2014; March 2026'),
  PB,
  h1('01 &#x2014; Executive Summary'),
  body('Comprehensive technical audit of the House of More Webflow site and its 30 Make.com automation scenarios. Covers site architecture, CMS data integrity, SEO coverage, CSS health, and automation logic across the full member lifecycle.'),
  sp(),
  body('Key metrics: 33 pages &#x2014; 7 CMS collections &#x2014; 32 components &#x2014; 1,743 Webflow styles &#x2014; 30 Make scenarios &#x2014; 5 external integrations.'),
  PB,
  h1('02 &#x2014; Site Structure'),
  sub('Pages (33 total)'),
  li('Public: Home, About, Experiences, Resources, For Hosts, Contact Us, Donation'),
  li('Auth flow: /log-in &#x2192; /sign-up &#x2192; /questionnaire &#x2192; /application-submitted'),
  li('Password recovery: /password/recover, /reset, /confirmation-page, /pending-member'),
  li('App area: /app/admin, /app/member'),
  li('CMS templates: Events, Events 2026, Experiences, Blogs, FAQs, Donations, Messages'),
  sp(),
  sub('Issues'),
  li('"components" page is published at /components &#x2014; should be draft'),
  li('"Untitled" page (untitled-2) is live with no purpose or content'),
  li('6 template pages had empty SEO &#x2014; fixed during this audit'),
  li('"sign-up" SEO title is "Untitled" &#x2014; requires fix'),
  PB,
  h1('03 &#x2014; CMS Collections'),
  sub('Events (Legacy) &#x2014; 116 items'),
  body('Built around TicketSpice. Minimal fields with no capacity, status, or gender logic. Likely stale and redundant with Events 2026.'),
  sp(),
  sub('Events 2026 &#x2014; 6 items'),
  li('Field slug typo: evente-record should be event-record'),
  li('Field "facilitator-id" is labeled "facilitator-email" &#x2014; misleading'),
  li('"Rebirthing Breathwork for Couples" has capacity 0 &#x2014; data entry error'),
  li('3 fields marked DO NOT FILL &#x2014; auto-filled by Make, visible to editors'),
  sp(),
  sub('Other Collections'),
  li('Donations: amount stored as PlainText, not Number &#x2014; financial data risk'),
  li('Blogs: missing author, publish date, excerpt, and category fields'),
  li('FAQs: Answer is PlainText &#x2014; no rich text formatting support'),
  li('Messages: To field is PlainText &#x2014; no referential integrity'),
  PB,
  h1('04 &#x2014; Components'),
  body('32 components across 5 groups. Structure is solid with clear separation of layout and UI.'),
  sp(),
  li('Typo: "quatity-wrapper" should be "quantity-wrapper"'),
  li('5 components have no group assigned &#x2014; harder to organize in Designer'),
  li('Modal trigger relies on #open-modal convention in description only'),
  PB,
  h1('05 &#x2014; Make Automation Scenarios'),
  sub('Overview &#x2014; 30 Scenarios'),
  li('25 webhook-triggered (CustomWebHook)'),
  li('3 Webflow-triggered: Add Event ID, Update Event, Delete Event'),
  li('2 scheduled: 7-day review, 24h reminder'),
  li('1 Memberstack-triggered: Delete member'),
  sp(),
  sub('Integrations'),
  li('HTTP &#x2014; external backend/database (20+ scenarios)'),
  li('Google Email &#x2014; all transactional notifications'),
  li('Stripe &#x2014; checkout and recurring payments'),
  li('Webflow CMS &#x2014; event sync'),
  li('Memberstack &#x2014; member lifecycle'),
  sp(),
  sub('Key Issues'),
  li('Missing error handlers on 2 critical scenarios (donation checkout, admin messaging)'),
  li('3 scenarios redundantly list events with overlapping logic'),
  li('"Admin List all Events" returns RSVP data &#x2014; misnamed'),
  li('"Facilitator List all events" returns data for one event only &#x2014; misnamed'),
  PB,
  h1('06 &#x2014; Fixes Applied This Session'),
  sub('SEO &#x2014; 5 Template Pages Updated'),
  li('Events 2026s: title = Event Name, description = event summary'),
  li('Events: title = Event Name, description = static fallback'),
  li('FAQs: title = Question, description = answer text'),
  li('Donations: title = Tier Name, description = tier description'),
  li('Messages: title = Subject, description = static fallback'),
  sp(),
  sub('Still Pending'),
  li('Fix sign-up SEO title'),
  li('Unpublish components and untitled-2 pages'),
  li('Fix capacity 0 on Rebirthing Breathwork event'),
  li('Rename evente-record field slug to event-record'),
].join('')));

// ── REPORT 2: SECURITY ────────────────────────────────────────────────────────
packDocx('02-Security-Report.docx', buildDoc([
  cover('HOUSE OF MORE', 'Security Audit Report &#x2014; March 2026'),
  PB,
  h1('01 &#x2014; Executive Summary'),
  body('Critical and high-severity security vulnerabilities identified across the 30 Make.com automation scenarios. Immediate action required on three critical findings before any further development. Two involve financial data and platform-wide access.'),
  PB,
  h1('02 &#x2014; Critical Findings'),
  sub('C1 &#x2014; Memberstack API Key Exposed in All 30 Blueprints'),
  body('The Memberstack secret key is hardcoded in plain text in every scenario blueprint file stored in the project repository. Anyone with repository access has full platform API access.'),
  li('Impact: Full read/write access to all member data, profiles, RSVPs, donations'),
  li('Fix: Rotate the key immediately in the Memberstack dashboard'),
  li('Then: Replace with Make connection manager across all 30 scenarios'),
  sp(),
  sub('C2 &#x2014; No Stripe Webhook Signature Verification'),
  body('Three donation scenarios accept Stripe webhook payloads without verifying the Stripe-Signature header. Any external actor can forge a Stripe event and create fake donation records.'),
  li('Donation &#x2014; Create Checkout session'),
  li('Member &#x2014; Donation &#x2014; Recurrent Donation &#x2014; Payment'),
  li('Member &#x2014; Donation one time &#x2014; checkout confirmation'),
  li('Fix: Verify Stripe-Signature header using the endpoint secret on every webhook receipt'),
  sp(),
  sub('C3 &#x2014; No Caller Identity Verification'),
  body('Member ID is passed from the frontend in 4 scenarios with no server-side validation. Any caller knowing a member ID can impersonate that member.'),
  li('Donation list my donations &#x2014; exposes another member\'s donation history'),
  li('G &#x2014; Member &#x2014; List My Events &#x2014; exposes another member\'s RSVPs'),
  li('H &#x2014; Member &#x2014; RSVP an event &#x2014; can RSVP as any member'),
  li('Member read message &#x2014; can mark any message as read by ID'),
  li('Fix: Validate member identity against the authenticated session token server-side'),
  PB,
  h1('03 &#x2014; High Severity'),
  sub('H1 &#x2014; Donation Amount Not Validated Server-Side'),
  li('The charge amount passes from frontend to Stripe without server-side validation'),
  li('A user can manipulate the request to submit an arbitrary amount'),
  li('Fix: Whitelist valid donation amounts server-side before passing to Stripe'),
  sp(),
  sub('H2 &#x2014; Silent Error Swallowing on Deletes'),
  li('Delete a Member table records: stopOnHttpError false &#x2014; profile data persists on failure'),
  li('Delete an Event from CMS: stopOnHttpError false &#x2014; event record persists on failure'),
  li('Fix: Set stopOnHttpError true and add error notification routing'),
  sp(),
  sub('H3 &#x2014; Race Condition on Capacity Decrement'),
  li('RSVP and check-in scenarios decrement capacity via non-atomic PUT operations'),
  li('Concurrent requests can over-book events'),
  li('Fix: Implement optimistic locking or queue-based capacity management'),
  sp(),
  sub('H4 &#x2014; Zero-Width Space in JSON Bodies'),
  li('Copy-paste artifact (U+200B) in 3 scenario request bodies can cause JSON parse errors'),
  li('Affected: Donation list all donations, I &#x2014; Admin List all rsvp, list all events'),
  PB,
  h1('04 &#x2014; Medium Severity'),
  sub('Hard Record Limits with No Pagination'),
  body('5 scenarios use take: 100 with no pagination. Data beyond 100 records is silently truncated and invisible to users and admins.'),
  sp(),
  sub('Other Issues'),
  li('Missing error handlers on donation checkout and admin messaging scenarios'),
  li('Hardcoded Webflow site/collection IDs in 5 scenarios &#x2014; breaks on site duplication'),
  li('Polling limited to 50 Webflow items in scheduled notification scenarios'),
  li('No deduplication guard &#x2014; 24h reminder can send duplicate emails'),
  li('records[1] hardcoded index in scenario C &#x2014; returns wrong data if array reorders'),
  li('submitted_at set to current time in scenario E &#x2014; not actual submission date'),
  PB,
  h1('05 &#x2014; Remediation Checklist'),
  sub('Immediate'),
  li('Rotate Memberstack API key in dashboard'),
  li('Replace hardcoded key with Make connection manager in all 30 scenarios'),
  li('Add Stripe webhook signature verification to 3 donation scenarios'),
  sp(),
  sub('This Week'),
  li('Add server-side identity validation to 4 member-facing scenarios'),
  li('Add server-side amount validation to Stripe checkout'),
  li('Fix zero-width space in 3 scenario JSON bodies'),
  li('Add error handlers to donation checkout and admin messaging'),
  sp(),
  sub('This Month'),
  li('Fix records[1] hardcoded index in scenario C'),
  li('Set stopOnHttpError true on both deletion scenarios'),
  li('Add pagination to all take: 100 queries'),
  li('Add deduplication flag to 24h reminder scenario'),
].join('')));

// ── REPORT 3: SEO ─────────────────────────────────────────────────────────────
packDocx('03-SEO-Report.docx', buildDoc([
  cover('HOUSE OF MORE', 'SEO Audit Report &#x2014; March 2026'),
  PB,
  h1('01 &#x2014; Executive Summary'),
  body('Audit of all 33 Webflow pages for SEO coverage, metadata quality, and Open Graph configuration. 5 template pages had completely empty SEO fields and were remediated live during this session.'),
  sp(),
  body('Status: 5 critical fixes applied and deployed. Additional issues remain on static utility pages.'),
  PB,
  h1('02 &#x2014; Strong Coverage'),
  sub('Pages with Complete SEO'),
  li('Home &#x2014; full title, description, Open Graph'),
  li('About &#x2014; full title, description, Open Graph'),
  li('Donation &#x2014; full title, description, Open Graph'),
  li('Experiences &#x2014; full title, description, Open Graph'),
  li('For Hosts &#x2014; full title, description, Open Graph'),
  li('Resources &#x2014; full title, description, Open Graph'),
  li('Contact Us &#x2014; full title, description, Open Graph'),
  li('Experiences Template &#x2014; dynamic {{wf}} bindings for title and description'),
  li('Blogs Template &#x2014; dynamic title binding'),
  PB,
  h1('03 &#x2014; Fixed During Audit'),
  sub('5 Template Pages Updated with Dynamic Webflow Bindings'),
  body('All remediated pages now use Webflow\'s {{wf}} dynamic field syntax, pulling CMS data per item. Open Graph is set to copy from SEO on all pages.'),
  sp(),
  li('Events 2026s Template &#x2014; [Event Name] &#x2014; House of More + event summary'),
  li('Events Template &#x2014; [Event Name] &#x2014; House of More Events + static fallback'),
  li('FAQs Template &#x2014; [Question] &#x2014; House of More FAQ + answer text'),
  li('Donations Template &#x2014; [Tier] &#x2014; Support House of More + tier description'),
  li('Messages Template &#x2014; [Subject] &#x2014; House of More Messages + static fallback'),
  PB,
  h1('04 &#x2014; Remaining Issues'),
  sub('Static Pages'),
  li('sign-up &#x2014; SEO title is "Untitled", no description'),
  li('untitled-2 &#x2014; published live, no real title or purpose'),
  li('components &#x2014; published at /components, should be draft'),
  li('cancel &#x2014; generic title, no description'),
  li('success &#x2014; generic title, no description'),
  li('application-submitted &#x2014; SEO title incorrectly says "success"'),
  sp(),
  sub('App and Auth Pages'),
  body('Pages under /app/ and /password/ serve authenticated users only and should not be indexed. A noindex robots meta tag is required via Webflow page settings.'),
  PB,
  h1('05 &#x2014; Recommendations'),
  sub('Structured Data'),
  body('Events and Experiences pages would benefit from JSON-LD structured data using the Event and Article schemas. This enables rich results in Google Search and improves click-through rates.'),
  sp(),
  sub('Action Items'),
  li('Fix sign-up SEO title and add description'),
  li('Set correct title and description on cancel, success, application-submitted'),
  li('Add noindex to all /app/* and /password/* pages'),
  li('Unpublish or delete untitled-2 and components pages'),
  li('Consider JSON-LD Event schema on Events 2026 template page'),
  li('Add OG image to all key marketing pages'),
].join('')));

// ── REPORT 4: CSS CLASSES ─────────────────────────────────────────────────────
packDocx('04-CSS-Classes-Report.docx', buildDoc([
  cover('HOUSE OF MORE', 'CSS Classes Cleanup Report &#x2014; March 2026'),
  PB,
  h1('01 &#x2014; Executive Summary'),
  body('Comprehensive audit of all 1,743 Webflow styles across 33 HTML pages, 3 JavaScript files, and all embedded code blocks. The audit identified 4 broken styles causing live UI failures, 12 missing state class definitions, and 216 styles confirmed safe for deletion.'),
  sp(),
  body('Scope: 864 CSS-defined classes &#x2014; 943 HTML class usages &#x2014; 92 JS class references &#x2014; all innerHTML patterns and embedded code blocks analyzed.'),
  PB,
  h1('02 &#x2014; Critical: 4 Broken Classes'),
  sub('Typos &#x2014; Defined Incorrectly, Never Match Elements'),
  body('These classes are defined in the stylesheet under misspelled names. The correct class names exist in the HTML but receive no styles. The mobile menu issue is live and affecting all mobile visitors.'),
  sp(),
  li('.rigth-arrow &#x2014; should be .right-arrow &#x2014; slider navigation arrows unstyled'),
  li('.selectot &#x2014; should be .selector &#x2014; form select inputs unstyled'),
  li('.dontation &#x2014; should be .donation &#x2014; donation UI components unstyled'),
  li('.hambuger-wrapper &#x2014; should be .hamburger-wrapper &#x2014; mobile menu broken'),
  sp(),
  body('Fix: In Webflow Designer, rename each class to its correct spelling. All elements using these classes will automatically receive their styles.'),
  PB,
  h1('03 &#x2014; Missing CSS Definitions'),
  sub('12 JS State Classes &#x2014; Toggled in Code, No Visual Effect'),
  body('These classes are added and removed via classList operations in embedded JavaScript. Without CSS definitions they produce no visual change when applied.'),
  sp(),
  li('accepted &#x2014; QR scanner check-in approved state'),
  li('rejected &#x2014; QR scanner and admin rejection state'),
  li('filled &#x2014; member profile form field state'),
  li('locked &#x2014; member profile form lock state'),
  li('canceled &#x2014; member RSVP cancellation state'),
  li('disable &#x2014; admin action button disabled state'),
  li('read &#x2014; message read/unread indicator'),
  li('sold &#x2014; sold-out event state'),
  li('ms-progress-active, ms-progress-complete, ms-progress-pending &#x2014; Memberstack progress steps'),
  li('ms-step-active &#x2014; Memberstack active questionnaire step'),
  sp(),
  sub('3 Responsive Utility Classes &#x2014; Used in HTML, No CSS'),
  li('hide-mobile-landscape &#x2014; elements are never hidden on landscape mobile'),
  li('hide-mobile-portrait &#x2014; elements are never hidden on portrait mobile'),
  li('hide-tablet &#x2014; elements are never hidden on tablet'),
  PB,
  h1('04 &#x2014; 216 Styles Safe to Delete'),
  sub('Breakdown'),
  li('14 Copy variants &#x2014; orphaned duplicates from Webflow duplicate action'),
  li('8 Invalid names &#x2014; aspect ratios (1:1, 4:3) and dot-prefixed class names'),
  li('111 Auto-numbered blocks &#x2014; Div Block N, Flex Block N, Text Block N'),
  li('61 Named orphaned styles &#x2014; defined but removed from all canvas elements'),
  sp(),
  sub('82 Styles That Must Be Kept'),
  li('15 HTML element styles &#x2014; h1 through h6, p, a, ul, li, ol, figure, blockquote'),
  li('42 Utility classes &#x2014; padding-*, text-style-*, icon-embed-*, container-large'),
  li('13 Style guide classes &#x2014; styleguide_* and rl-styleguide_*'),
  li('12 JS state classes &#x2014; hide, active, is-today, is-selected, has-event, and others'),
  PB,
  h1('05 &#x2014; Naming Inconsistencies'),
  sub('38 Classes Using Underscore Instead of Kebab-Case'),
  li('content_wrapper, hero_button, hero_image, global_padding, page_wrapper, icon_hide'),
  li('blog_rich-text, cursive_span, hosting_heading, grid_12, grid_std'),
  sp(),
  sub('Duplicate Concepts'),
  li('global_padding AND padding-global both exist &#x2014; same concept, two classes'),
  li('left-arrow2 AND left-arrow-2 both exist &#x2014; inconsistent numeric suffix'),
  sp(),
  sub('Spelling Errors in Class Names'),
  li('experience-carrousel &#x2014; should be experience-carousel'),
  li('form-wraper &#x2014; should be form-wrapper'),
  li('evevtdata &#x2014; should be eventdata'),
  li('message-already-booke &#x2014; should be message-already-booked'),
  PB,
  h1('06 &#x2014; Cleanup Instructions'),
  sub('How to Delete Unused Styles in Webflow'),
  body('The Webflow API does not support style deletion. All cleanup must be done through the Webflow Designer Style Manager.'),
  sp(),
  li('Step 1: Open Designer &#x2192; Styles panel (paintbrush icon) &#x2192; click Clean Up'),
  li('Step 2: Review flagged styles against this report and delete confirmed safe items'),
  li('Step 3: Search and delete the 14 copy variants and 61 named orphans manually'),
  li('Step 4: Fix the 4 typo class names by renaming in the Styles panel'),
  li('Step 5: Add CSS definitions for the 12 missing JS state classes'),
  sp(),
  sub('Priority Order'),
  li('First: Fix 4 typos &#x2014; live UI issues affecting mobile users now'),
  li('Second: Add CSS for 12 missing state classes &#x2014; silent UI bugs'),
  li('Third: Run Clean Up to remove auto-numbered styles'),
  li('Fourth: Manually delete copy variants and named orphans'),
  li('Fifth: Standardize 38 underscore classes to kebab-case'),
].join('')));

console.log('\nAll 4 reports generated in:', OUTPUT_DIR);
